### ISSUE TITLE
More flexible values for arg list / kwargs dict

### ISSUE THREAD

**Issue by jayvdb** [hairetdin/django-dmcadmin#1]
It would be nice if the run UI allowed arg list & kwargs dict to be empty.
A lot of management commands dont require any args, and it isnt very ambiguous if these fields are empty.  If a command really needs an empty arg, the user can put `['']` into the arg list, which they already need to do.

It would also be nice if the arg list defaulted to parsing the value as a string with args space separated.  i.e. `foo bar` became `['foo', 'bar']` .  Management commands are usually documented in command line invocation style of `./manage cmd arg1 arg2` , so it would be more intuitive if the dmcadmin UI used a simplistic approach for that.  The existing handling of explicit `[...]` would still be needed.  The two modes of values are disjoint based on whether the first character is a `[`.

**Comment by hairetdin** [comment]
I agree, I'll finalize

**Comment by hairetdin** [comment]
Added the ability to write arguments and options as a string. 
Run the command to update: `pip install --upgrade django-dmcadmin`
